### ISSUE TITLE
support word pos in cut for search?

### ISSUE THREAD

**Issue by swuecho** [iynehz/perl5-jieba#5]
Thanks for writing the Perl binding. I was trying, but not enough low level experience.

I was using Inline::Python before and have a use case like this.

```
result = jieba.tokenize(u'永和服装饰品有限公司', mode='search')
for tk in result:
    print("word %s\t\t start: %d \t\t end:%d" % (tk[0],tk[1],tk[2]))
```

```
word 永和                start: 0                end:2
word 服装                start: 2                end:4
word 饰品                start: 4                end:6
word 有限公司            start: 6                end:10

```

I wonder if it is possible to support this in the perl binding? Thanks.

**Comment by iynehz** [comment]
I see CppJieba, which this Perl module binds to, can support a word/offset/length struct for cut result. I will see if I can make that available from the Perl module during the coming holidays.

**Comment by swuecho** [comment]
Thanks. looking forward to it.

**Comment by iynehz** [comment]
I've released a new version to CPAN https://metacpan.org/pod/distribution/Lingua-ZH-Jieba/lib/Lingua/ZH/Jieba.pod

Now you can do it like this, 

```perl
use strict;
use warnings;
use Lingua::ZH::Jieba;
 
binmode STDOUT, ":utf8";
 
my $jieba = Lingua::ZH::Jieba->new();
my $result = $jieba->cut_for_search_ex('永和服装饰品有限公司');
for my $tk (@$result) {
    printf "word %s\t\t offset: %d\t\t length: %d\n", @$tk;
}
```

**Comment by swuecho** [comment]
Thank you very much!
